# Persistent Volume Claim
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: portfolio-pvc
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: longhorn
#   resources:
#     requests:
#       storage: 1Gi

---
# Deployment Object
apiVersion: apps/v1
kind: Deployment
metadata:
  name: warranty-management-be-deployment-dev
spec:
  selector:
    matchLabels:
      app: warranty-management-be-dev
  replicas: 2
  template:
    metadata:
      labels:
        app: warranty-management-be-dev
    spec:
      containers:
      - name: warranty-management-be-dev
        image: fleeforezz/warranty-management-be:1.18-beta
        resources:
          limits:
            cpu: "1000m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        # volumeMounts:
        # - mountPath: "/"
        #   name: portfolio-storage
        ports:
        - containerPort: 9455
      # volumes:
      # - name: portfolio-storage
      #   persistentVolumeClaim:
      #     claimName: portfolio-pvc
      automountServiceAccountToken: false

---

# Service Object
apiVersion: v1
kind: Service
metadata:
  name: warranty-management-be-service-dev
spec:
  selector:
    app: warranty-management-be-dev
  type: NodePort
  ports:
    - port: 9455
      targetPort: 9455
      nodePort: 32525